const dummyMixItems = [
	{
		itemName: "Almond",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "95.00",
	},
	{
		itemName: "Bush Rice Color",
		itemDescription: "",
		itemQuantity: "100g",
		itemPrice: "16.00",
	},
	{
		itemName: "Cashew",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "150.00",
	},
	{
		itemName: "Ching Sauce",
		itemDescription: "Any",
		itemQuantity: "200gm",
		itemPrice: "15.00",
	},
	{
		itemName: "Custard",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "15.00",
	},
	{
		itemName: "Dabur Honey",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "30.00",
	},
	{
		itemName: "Eno",
		itemDescription: "3 Flavours/pouch",
		itemQuantity: "1",
		itemPrice: "25.00",
	},
	{
		itemName: "Funfood Mayonise",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "25.00",
	},
	{
		itemName: "Gulab Syrup",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "28.00",
	},
	{
		itemName: "Haldi",
		itemDescription: "Turmeric",
		itemQuantity: "400gm",
		itemPrice: "30.00",
	},
	{
		itemName: "Haldirams Ras Gulla",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "28.00",
	},
	{
		itemName: "Haldirams Gulab Jamun",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "28.00",
	},
	{
		itemName: "Imli",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "12.00",
	},
	{
		itemName: "Jaggery",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "35.00",
	},
	{
		itemName: "Jk Black Pepper",
		itemDescription: "Whole",
		itemQuantity: "100gm",
		itemPrice: "18.00",
	},
	{
		itemName: "Jk Spices",
		itemDescription: "Any",
		itemQuantity: "1",
		itemPrice: "10.00",
	},
	{
		itemName: "Kissan Jam",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "30.00",
	},
	{
		itemName: "Maggi",
		itemDescription: "Available in 3 sizes for $4/$12/$20",
		itemQuantity: "1",
		itemPrice: "4.00",
	},
	{
		itemName: "Maggi Sauce",
		itemDescription: "500gm & 1kg available",
		itemQuantity: "500gm",
		itemPrice: "25.00",
	},
	{
		itemName: "Maggi Sauce",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "40.00",
	},
	{
		itemName: "Mango Pulp",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "28.00",
	},
	{
		itemName: "Mumra",
		itemDescription: "",
		itemQuantity: "500gm",
		itemPrice: "20.00",
	},
	{
		itemName: "Nutrella",
		itemDescription: "",
		itemQuantity: "200gm",
		itemPrice: "12.00",
	},
	{
		itemName: "Phool Makhana",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "25.00",
	},
	{
		itemName: "Poha",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "13.00",
	},
	{
		itemName: "Raw Peanuts",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "28.00",
	},
	{
		itemName: "Roasted Black Channa",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "20.00",
	},
	{
		itemName: "Rusk",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "14.00",
	},
	{
		itemName: "Almond",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "95.00",
	},
	{
		itemName: "Schezwaan Noodles",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "15.00",
	},
	{
		itemName: "Veg Hakka Noodles",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
	},
	{
		itemName: "Honey",
		itemDescription: "Available in 3 sizes",
		itemQuantity: "1",
		itemPrice: "24.00",
	},
	{
		itemName: "Honey",
		itemDescription: "Available in 3 sizes",
		itemQuantity: "1",
		itemPrice: "45.00",
	},
	{
		itemName: "Honey",
		itemDescription: "Available in 3 sizes",
		itemQuantity: "1",
		itemPrice: "80.00",
	},
	{
		itemName: "Vermicilly",
		itemDescription: "",
		itemQuantity: "200gm",
		itemPrice: "14.00",
	},
	{
		itemName: "Tata Salt",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "9.00",
	},
	{
		itemName: "Sugar",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "10.00",
	},
	{
		itemName: "Taramind",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "12.00",
	},
	{
		itemName: "Schezwahn Sauce",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "17.00",
	},
	{
		itemName: "Real Lemon",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "25.00",
	},
	{
		itemName: "Ready to Eat",
		itemDescription: "Punjabi Cholle, Dal Makhani, Matar Paneer",
		itemQuantity: "1",
		itemPrice: "18.00",
	},
	{
		itemName: "Patanjali Tooth",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "14.00",
	},
	{
		itemName: "Santoor Soap",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
	},
	{
		itemName: "Monaco Biscuit",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "3.00",
	},
	{
		itemName: "Limka",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "7.00",
	},
	{
		itemName: "Badam Milk",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "7.00",
	},
	{
		itemName: "Laziza Kheer",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "14.00",
	},
	{
		itemName: "Mehandi Cone",
		itemDescription: "Singh",
		itemQuantity: "1",
		itemPrice: "8.00",
	},
	{
		itemName: "Himalaya Neem Soap",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "13.00",
	},
	{
		itemName: "Himalaya Neem Face Wash",
		itemDescription: "",
		itemQuantity: "300ml",
		itemPrice: "50.00",
	},
	{
		itemName: "Dabur Hajmola",
		itemDescription: "Pudhina, Plain and Anardana",
		itemQuantity: "1",
		itemPrice: "14.00",
	},
	{
		itemName: "Dabur Gulabari",
		itemDescription: "Rose Water",
		itemQuantity: "1",
		itemPrice: "20.00",
	},
	{
		itemName: "Coconut Powder",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "30.00",
	},
	{
		itemName: "Coconut Milk",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "15.00",
	},
	{
		itemName: "Bikano Papad Amritsar",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "14.00",
	},
	{
		itemName: "Lijjat Papad",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
	},
	{
		itemName: "Agarbatti",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "6.00",
	},
	{
		itemName: "Bornvita",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "40.00",
	},
	{
		itemName: "Khari",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "15.00",
	},
	{
		itemName: "Himani Navratan Oil",
		itemDescription: "",
		itemQuantity: "300ml",
		itemPrice: "38.00",
	},
	{
		itemName: "Himani Navratan Oil",
		itemDescription: "",
		itemQuantity: "200ml",
		itemPrice: "30.00",
	},
	{
		itemName: "Almond Oil",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "40.00",
	},
	{
		itemName: "Dabur Oil",
		itemDescription: "",
		itemQuantity: "450ml",
		itemPrice: "35.00",
	},
	{
		itemName: "Dabur Oil",
		itemDescription: "",
		itemQuantity: "275ml",
		itemPrice: "28.00",
	},
	{
		itemName: "Haldiram Snacks",
		itemDescription: "Any",
		itemQuantity: "1",
		itemPrice: "10.00",
	},
	{
		itemName: "Fresh Kowloon Dairy Milk",
		itemDescription: "Any",
		itemQuantity: "1",
		itemPrice: "20.00",
	},
	{
		itemName: "Bornbon",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "20.00",
	},
	{
		itemName: "Cake Rusk",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "19.00",
	},
	{
		itemName: "Cake Rusk",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "40.00",
	},
	{
		itemName: "Good Day Butter",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "44.00",
	},
	{
		itemName: "Good Day Cashews",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "40.00",
	},
	{
		itemName: "Good Day Pista",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "48.00",
	},
	{
		itemName: "Milk Bikkis",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "5.00",
	},
	{
		itemName: "Exo",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
	},
	{
		itemName: "Tutti Frutti",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
	},
	{
		itemName: "Parle G Biscuit",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "25.00",
	},
	{
		itemName: "Baking Powder",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
	},
	{
		itemName: "Baking Soda",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
	},
	{
		itemName: "Fenugreek Seed",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
	},
	{
		itemName: "Tukmanga",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "12.00",
	},
	{
		itemName: "Khaskhas",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "28.00",
	},
	{
		itemName: "Flex Seed",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "18.00",
	},
	{
		itemName: "Roasted Channa Split",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "22.00",
	},
];
