export const dummyAtta = [
	{
		itemName: "Rice Atta",
		itemDescription: "",
		itemQuantity: "500gm",
		itemPrice: "10.00",
		category: "Atta",
	},
	{
		itemName: "Rajdhani Sooji",
		itemDescription: "",
		itemQuantity: "500gm",
		itemPrice: "10.00",
		category: "Atta",
	},
	{
		itemName: "Makki Atta",
		itemDescription: "",
		itemQuantity: "500gm",
		itemPrice: "10.00",
		category: "Atta",
	},
	{
		itemName: "Juwar/Bajra Atta",
		itemDescription: "",
		itemQuantity: "500gm",
		itemPrice: "10.00",
		category: "Atta",
	},
	{
		itemName: "Rajdhani Maida",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "12.00",
		category: "Atta",
	},
	{
		itemName: "Dalia",
		itemDescription: "",
		itemQuantity: "500gm",
		itemPrice: "12.00",
		category: "Atta",
	},
	{
		itemName: "Channa Sattu",
		itemDescription: "",
		itemQuantity: "500gm",
		itemPrice: "14.00",
		category: "Atta",
	},
	{
		itemName: "Rajdhani Besan",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "20.00",
		category: "Atta",
	},
	{
		itemName: "Ragi Atta",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "22.00",
		category: "Atta",
	},
	{
		itemName: "Pillsbury Chakki",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "45.00",
		category: "Atta",
	},
	{
		itemName: "Aashirwaad",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "45.00",
		category: "Atta",
	},
	{
		itemName: "Pillsbury Gold",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "50.00",
		category: "Atta",
	},
	{
		itemName: "Aashirwaad Select",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "50.00",
		category: "Atta",
	},
	{
		itemName: "Pillsbury Multigrand",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "55.00",
		category: "Atta",
	},
	{
		itemName: "Aashirwaad Multigrand",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "55.00",
		category: "Atta",
	},
];
export const dummyMilks = [
	{
		itemName: "Amur Taaza",
		itemDescription: "",
		itemQuantity: "12 x 1litre",
		itemPrice: "138.00",
		category: "Milks",
	},
	{
		itemName: "Amur Taaza Gold",
		itemDescription: "",
		itemQuantity: "12 x 1litre",
		itemPrice: "150.00",
		category: "Milks",
	},
	{
		itemName: "Pauls Long Life UHT",
		itemDescription: "",
		itemQuantity: "12 x 1litre",
		itemPrice: "145.00",
		category: "Milks",
	},
	{
		itemName: "Dairy Farm UHT",
		itemDescription: "",
		itemQuantity: "12 x 1litre",
		itemPrice: "150.00",
		category: "Milks",
	},
	{
		itemName: "Goodwell",
		itemDescription: "",
		itemQuantity: "12 x 1litre",
		itemPrice: "130.00",
		category: "Milks",
	},
	{
		itemName: "Double Happiness Milk",
		itemDescription: "",
		itemQuantity: "1 Can",
		itemPrice: "8.00",
		category: "Milks",
	},
	{
		itemName: "Coconut Milk",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "15.00",
		category: "Milks",
	},
	{
		itemName: "Badam Milk",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "7.00",
		category: "Milks",
	},
	{
		itemName: "Fresh Kowloon Dairy Milk",
		itemDescription: "Any",
		itemQuantity: "1",
		itemPrice: "20.00",
		category: "Milks",
	},
];
export const dummyGhee = [
	{
		itemName: "Gowardhan",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "78.00",
		category: "Ghee",
	},
	{
		itemName: "Lelia",
		itemDescription: "",
		itemQuantity: "800g",
		itemPrice: "78.00",
		category: "Ghee",
	},
	{
		itemName: "Amul",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "65.00",
		category: "Ghee",
	},
	{
		itemName: "Amul Pure Cow",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "75.00",
		category: "Ghee",
	},
	{
		itemName: "Verka",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "65.00",
		category: "Ghee",
	},
	{
		itemName: "Everyday",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "65.00",
		category: "Ghee",
	},
	{
		itemName: "Patanjali",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "80.00",
		category: "Ghee",
	},
	{
		itemName: "Nanak Desi Ghee",
		itemDescription: "",
		itemQuantity: "800g",
		itemPrice: "82.00",
		category: "Ghee",
	},
];
export const dummyTea = [
	{
		itemName: "Girnar Tea",
		itemDescription: "Ginger/Masala/Cinemon",
		itemQuantity: "1",
		itemPrice: "30.00",
		category: "Tea",
	},
	{
		itemName: "Red Label",
		itemDescription: "250gm/500gm available",
		itemQuantity: "250gm",
		itemPrice: "20",
		category: "Tea",
	},
	{
		itemName: "Tata Tea Gold",
		itemDescription: "",
		itemQuantity: "500gm",
		itemPrice: "38.00",
		category: "Tea",
	},
	{
		itemName: "Taj Mahal",
		itemDescription: "",
		itemQuantity: "250gm",
		itemPrice: "25.00",
		category: "Tea",
	},
	{
		itemName: "Everest",
		itemDescription: "",
		itemQuantity: "250gm",
		itemPrice: "15.00",
		category: "Tea",
	},
	{
		itemName: "Tea Masala",
		itemDescription: "",
		itemQuantity: "100gm",
		itemPrice: "20.00",
		category: "Tea",
	},
	{
		itemName: "Society Tea",
		itemDescription: "250gm/500gm available",
		itemQuantity: "250gm",
		itemPrice: "22.00",
		category: "Tea",
	},
	{
		itemName: "Wagh Bakri Tea",
		itemDescription: "250gm/500gm available",
		itemQuantity: "250gm",
		itemPrice: "22.00",
		category: "Tea",
	},
	{
		itemName: "Wagh Bakri Tea",
		itemDescription: "",
		itemQuantity: "500gm",
		itemPrice: "38.00",
		category: "Tea",
	},
	{
		itemName: "Tata Premium",
		itemDescription: "250/500g & 1kg available",
		itemQuantity: "250gm",
		itemPrice: "22.00",
		category: "Tea",
	},
	{
		itemName: "Tata Premium",
		itemDescription: "250/500g & 1kg available",
		itemQuantity: "500gm",
		itemPrice: "40.00",
		category: "Tea",
	},
	{
		itemName: "Tata Premium",
		itemDescription: "250/500g & 1kg available",
		itemQuantity: "1kg",
		itemPrice: "70.00",
		category: "Tea",
	},
	{
		itemName: "Lipton",
		itemDescription: "",
		itemQuantity: "100 bags",
		itemPrice: "32.00",
		category: "Tea",
	},
];
export const dummyPickelsChutneysSauces = [
	{
		itemName: "Kicthen Express",
		itemDescription: "Mix Pickle",
		itemQuantity: "400gm",
		itemPrice: "15.00",
		category: "Pickles & Sauces",
	},
	{
		itemName: "Mother Pickle Mix",
		itemDescription: "",
		itemQuantity: "400gm",
		itemPrice: "15.00",
		category: "Pickles & Sauces",
	},
	{
		itemName: "National Mix Pickle",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "30.00",
		category: "Pickles & Sauces",
	},
	{
		itemName: "National Mango Pickle",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "30.00",
		category: "Pickles & Sauces",
	},
	{
		itemName: "Mayonise Sauces",
		itemDescription: "Any",
		itemQuantity: "1",
		itemPrice: "25.00",
		category: "Pickles & Sauces",
	},
	{
		itemName: "Priya",
		itemDescription: "Any",
		itemQuantity: "300gm × 1",
		itemPrice: "18.00",
		category: "Pickles & Sauces",
	},
	{
		itemName: "Mothers",
		itemDescription: "All Mothers chutneys & sauces available",
		itemQuantity: "",
		itemPrice: "",
		category: "Pickles & Sauces",
	},
	{
		itemName: "Ching Sauce",
		itemDescription: "Any",
		itemQuantity: "200gm",
		itemPrice: "15.00",
		category: "Pickles & Sauces",
	},
	{
		itemName: "Funfood Mayonise",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "25.00",
		category: "Pickles & Sauces",
	},
	{
		itemName: "Maggi Sauce",
		itemDescription: "500gm & 1kg available",
		itemQuantity: "500gm",
		itemPrice: "25.00",
		category: "Pickles & Sauces",
	},
	{
		itemName: "Maggi Sauce",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "40.00",
		category: "Pickles & Sauces",
	},
	{
		itemName: "Schezwahn Sauce",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "17.00",
		category: "Pickles & Sauces",
	},
];
export const dummyOil = [
	{
		itemName: "Mustard Oil",
		itemDescription: "Sarsola",
		itemQuantity: "500g",
		itemPrice: "20.00",
		category: "Oil",
	},
	{
		itemName: "Fortune Mustard",
		itemDescription: "",
		itemQuantity: "1ltr",
		itemPrice: "35.00",
		category: "Oil",
	},
	{
		itemName: "Safola Gold",
		itemDescription: "",
		itemQuantity: "5ltr",
		itemPrice: "150.00",
		category: "Oil",
	},
	{
		itemName: "Sunflower",
		itemDescription: "",
		itemQuantity: "5ltr",
		itemPrice: "90.00",
		category: "Oil",
	},
	{
		itemName: "Wesson Veg Oil",
		itemDescription: "",
		itemQuantity: "5ltr",
		itemPrice: "90.00",
		category: "Oil",
	},
	{
		itemName: "Sunflower",
		itemDescription: "",
		itemQuantity: "1ltr",
		itemPrice: "20.00",
		category: "Oil",
	},
	{
		itemName: "Sunflower",
		itemDescription: "",
		itemQuantity: "2ltr",
		itemPrice: "40.00",
		category: "Oil",
	},
	{
		itemName: "Olive Pomale Oil",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "150.00",
		category: "Oil",
	},
	{
		itemName: "Soya Bean Oil",
		itemDescription: "",
		itemQuantity: "15ltr",
		itemPrice: "150.00",
		category: "Oil",
	},
	{
		itemName: "Castor Oil",
		itemDescription: "",
		itemQuantity: "250ml",
		itemPrice: "46.00",
		category: "Oil",
	},
	{
		itemName: "Kolonji Oil",
		itemDescription: "",
		itemQuantity: "100ml",
		itemPrice: "40.00",
		category: "Oil",
	},
	{
		itemName: "Idhayan Oil",
		itemDescription: "200/500ml & 1ltr available",
		itemQuantity: "200ml",
		itemPrice: "15.00",
		category: "Oil",
	},
	{
		itemName: "Idhayan Oil",
		itemDescription: "200/500ml & 1ltr available",
		itemQuantity: "500ml",
		itemPrice: "40.00",
		category: "Oil",
	},
	{
		itemName: "Idhayan Oil",
		itemDescription: "200/500ml & 1ltr available",
		itemQuantity: "1ltr",
		itemPrice: "60.00",
		category: "Oil",
	},
	{
		itemName: "Parachute Oil",
		itemDescription: "500ml & 1ltr available",
		itemQuantity: "500ml",
		itemPrice: "33.00",
		category: "Oil",
	},
	{
		itemName: "Parachute Oil",
		itemDescription: "",
		itemQuantity: "1ltr",
		itemPrice: "60.00",
		category: "Oil",
	},
];
export const dummyDal = [
	{
		itemName: "Rajdhana",
		itemDescription: "Any",
		itemQuantity: "1kg",
		itemPrice: "20.00",
		category: "Dal",
	},
	{
		itemName: "Nanki Dal",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "20.00",
		category: "Dal",
	},
	{
		itemName: "Rajmaa",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "22.00",
		category: "Dal",
	},
];
export const dummy1kgRice = [
	{
		itemName: "India Gate Classic",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "28.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "India Gate Super",
		itemDescription: "",
		itemQuantity: "1.25kg",
		itemPrice: "25.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "Parliament Brown Rice",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "25.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "Kohinoor Extra Long",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "24.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "Kohinoor Traditional",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "24.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "Kalyani Surti Kolam",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "22.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "Kalyani Ponni Raw",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "18.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "Kalyani Ponni Boiled",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "18.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "Kalyani Sona Masuri",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "18.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "Kalyani Idly",
		itemDescription: "1kg/5kg available",
		itemQuantity: "1kg",
		itemPrice: "16.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "Kalyani Idly",
		itemDescription: "1kg/5kg available",
		itemQuantity: "5kg",
		itemPrice: "70.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "Charminar",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "15.00",
		category: "Rice(small packing)",
	},
	{
		itemName: "Parliament",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "15.00",
		category: "Rice(small packing)",
	},
];
export const dummy5kgRice = [
	{
		itemName: "Daawat Biryani",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "120.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Daawat Traditional",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "120.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "India Gate Super",
		itemDescription: "",
		itemQuantity: "6.5kg",
		itemPrice: "120.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Kohinoor Extra Long",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "120.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Kohinoor Blue",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "120.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Kalyani Surti Kolan",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "110.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Daawat Rozana",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "80.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Lal Qilla Majestix",
		itemDescription: "Extra Long",
		itemQuantity: "5kg",
		itemPrice: "95.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "National Rice",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "90.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Lal Qilla Supreme Sella",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "90.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Parliament Classic",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "90.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Parliament Extra Long",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "90.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Daawat Everyday",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "75.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Charminar",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "75.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Kitchen King Sona Masoori",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "75.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Parliament Dairy Delight",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "70.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Charminar Rozanna",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "70.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Kitchen King Ponni Raw",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "70.00",
		category: "Rice(big packing)",
	},
	{
		itemName: "Kitchen King Ponni Boiled",
		itemDescription: "",
		itemQuantity: "5kg",
		itemPrice: "70.00",
		category: "Rice(big packing)",
	},
];
export const SpicesAndCondiments = [
	{
		itemName: "MDH Masala",
		itemDescription: "Any",
		itemQuantity: "1",
		itemPrice: "12.00",
		category: "Spices & Condiments",
	},
	{
		itemName: "Everest Masala",
		itemDescription: "Any",
		itemQuantity: "1",
		itemPrice: "12.00",
		category: "Spices & Condiments",
	},
	{
		itemName: "Shan Masala",
		itemDescription: "Any",
		itemQuantity: "1",
		itemPrice: "12.00",
		category: "Spices & Condiments",
	},
	{
		itemName: "Jk Black Pepper",
		itemDescription: "Whole",
		itemQuantity: "100gm",
		itemPrice: "18.00",
		category: "Spices & Condiments",
	},
	{
		itemName: "Jk Spices",
		itemDescription: "Any",
		itemQuantity: "1",
		itemPrice: "10.00",
		category: "Spices & Condiments",
	},
	{
		itemName: "Haldi",
		itemDescription: "Turmeric",
		itemQuantity: "400gm",
		itemPrice: "30.00",
		category: "Spices & Condiments",
	},
];

export const dummyDryFruits = [
	{
		itemName: "Almond",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "95.00",
		category: "Dry Fruits",
	},
	{
		itemName: "Cashew",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "150.00",
		category: "Dry Fruits",
	},
	{
		itemName: "Phool Makhana",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "25.00",
		category: "Dry Fruits",
	},
	{
		itemName: "Raw Peanuts",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "28.00",
		category: "Dry Fruits",
	},
];
export const dummyPersonalCare = [
	{
		itemName: "Patanjali Tooth",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "14.00",
		category: "Household Items",
	},
	{
		itemName: "Santoor Soap",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
		category: "Household Items",
	},
	{
		itemName: "Mehandi Cone",
		itemDescription: "Singh",
		itemQuantity: "1",
		itemPrice: "8.00",
		category: "Household Items",
	},
	{
		itemName: "Himalaya Neem Soap",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "13.00",
		category: "Household Items",
	},
	{
		itemName: "Himalaya Neem Face Wash",
		itemDescription: "",
		itemQuantity: "300ml",
		itemPrice: "50.00",
		category: "Household Items",
	},
	{
		itemName: "Dabur Gulabari",
		itemDescription: "Rose Water",
		itemQuantity: "1",
		itemPrice: "20.00",
		category: "Household Items",
	},
];

export const dummyOtherItems = [
	{
		itemName: "Bush Rice Color",
		itemDescription: "",
		itemQuantity: "100g",
		itemPrice: "16.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Eno",
		itemDescription: "3 Flavours/pouch",
		itemQuantity: "1",
		itemPrice: "25.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Gulab Syrup",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "28.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Imli",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "12.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Jaggery",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "35.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Mango Pulp",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "28.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Roasted Black Channa",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "20.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Tata Salt",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "9.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Sugar",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "10.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Taramind",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "12.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Dabur Hajmola",
		itemDescription: "Pudhina, Plain and Anardana",
		itemQuantity: "1",
		itemPrice: "14.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Coconut Powder",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "30.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Agarbatti",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "6.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Khari",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "15.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Himani Navratan Oil",
		itemDescription: "",
		itemQuantity: "300ml",
		itemPrice: "38.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Himani Navratan Oil",
		itemDescription: "",
		itemQuantity: "200ml",
		itemPrice: "30.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Almond Oil",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "40.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Dabur Oil",
		itemDescription: "",
		itemQuantity: "450ml",
		itemPrice: "35.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Dabur Oil",
		itemDescription: "",
		itemQuantity: "275ml",
		itemPrice: "28.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Baking Powder",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Baking Soda",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
		category: "Other Grocery Items",
	},
	{
		itemName: "Real Lemon",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "25.00",
		category: "Other Grocery Items",
	},
];
export const dummyReadyToEat = [
	{
		itemName: "Punjabi Cholle",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "18.00",
		category: "Ready To Eat",
	},
	{
		itemName: "Dal Makhani",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "18.00",
		category: "Ready To Eat",
	},
	{
		itemName: "Matar Paneer",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "18.00",
		category: "Ready To Eat",
	},
];

export const dummyPackedFoods = [
	{
		itemName: "Custard",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "15.00",
		category: "Packed Foods",
	},
	{
		itemName: "Dabur Honey",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "30.00",
		category: "Packed Foods",
	},
	{
		itemName: "Kissan Jam",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "30.00",
		category: "Packed Foods",
	},
	{
		itemName: "Maggi",
		itemDescription: "Available in 3 sizes for $4/$12/$20",
		itemQuantity: "1",
		itemPrice: "4.00",
		category: "Packed Foods",
	},
	{
		itemName: "Mumra",
		itemDescription: "",
		itemQuantity: "500gm",
		itemPrice: "20.00",
		category: "Packed Foods",
	},
	{
		itemName: "Nutrella",
		itemDescription: "",
		itemQuantity: "200gm",
		itemPrice: "12.00",
		category: "Packed Foods",
	},
	{
		itemName: "Poha",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "13.00",
		category: "Packed Foods",
	},
	{
		itemName: "Schezwaan Noodles",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "15.00",
		category: "Packed Foods",
	},
	{
		itemName: "Veg Hakka Noodles",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
		category: "Packed Foods",
	},
	{
		itemName: "Honey",
		itemDescription: "Available in 3 sizes",
		itemQuantity: "1",
		itemPrice: "24.00",
		category: "Packed Foods",
	},
	{
		itemName: "Honey",
		itemDescription: "Available in 3 sizes",
		itemQuantity: "1",
		itemPrice: "45.00",
		category: "Packed Foods",
	},
	{
		itemName: "Honey",
		itemDescription: "Available in 3 sizes",
		itemQuantity: "1",
		itemPrice: "80.00",
		category: "Packed Foods",
	},
	{
		itemName: "Vermicilly",
		itemDescription: "",
		itemQuantity: "200gm",
		itemPrice: "14.00",
		category: "Packed Foods",
	},
	{
		itemName: "Bikano Papad Amritsar",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "14.00",
		category: "Packed Foods",
	},
	{
		itemName: "Lijjat Papad",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
		category: "Packed Foods",
	},
	{
		itemName: "Bornvita",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "40.00",
		category: "Packed Foods",
	},
];
export const dummyFrozenItems = [
	{
		itemName: "Paneer Kitching King",
		itemDescription: "200gm & 1kg available",
		itemQuantity: "200g",
		itemPrice: "14.00",
		category: "Frozen Items",
	},
	{
		itemName: "Amul Paneer",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "70.00",
		category: "Frozen Items",
	},
	{
		itemName: "Nanak Paneer",
		itemDescription: "",
		itemQuantity: "200gm",
		itemPrice: "15.00",
		category: "Frozen Items",
	},
	{
		itemName: "Amul Proceed Cheese Cubes",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "30.00",
		category: "Frozen Items",
	},
	{
		itemName: "Amul Cheese Slices",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "30.00",
		category: "Frozen Items",
	},
	{
		itemName: "Amul Procees Cheese Tin",
		itemDescription: "",
		itemQuantity: "400gm",
		itemPrice: "35.00",
		category: "Frozen Items",
	},
	{
		itemName: "Amul Cheddar Cheese",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "80.00",
		category: "Frozen Items",
	},
	{
		itemName: "Amul Mozzerla Cheese",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "85.00",
		category: "Frozen Items",
	},
	{
		itemName: "Amul Butter",
		itemDescription: "",
		itemQuantity: "500gm",
		itemPrice: "38.00",
		category: "Frozen Items",
	},
	{
		itemName: "Milk Magic Mozzrela Shredded",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "70.00",
		category: "Frozen Items",
	},
	{
		itemName: "Suvai Dosa Batter",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "35.00",
		category: "Frozen Items",
	},
	{
		itemName: "Suvai Grated Coconut",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "24.00",
		category: "Frozen Items",
	},
];

export const dummySnacks = [
	{
		itemName: "Haldirams Ras Gulla",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "28.00",
		category: "Snacks",
	},
	{
		itemName: "Haldirams Gulab Jamun",
		itemDescription: "",
		itemQuantity: "1kg",
		itemPrice: "28.00",
		category: "Snacks",
	},
	{
		itemName: "Rusk",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "14.00",
		category: "Snacks",
	},
	{
		itemName: "Monaco Biscuit",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "3.00",
		category: "Snacks",
	},
	{
		itemName: "Limka",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "7.00",
		category: "Snacks",
	},
	{
		itemName: "Laziza Kheer",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "14.00",
		category: "Snacks",
	},
	{
		itemName: "Haldiram Snacks",
		itemDescription: "Any",
		itemQuantity: "1",
		itemPrice: "10.00",
		category: "Snacks",
	},
	{
		itemName: "Bornbon",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "20.00",
		category: "Snacks",
	},
	{
		itemName: "Cake Rusk",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "19.00",
		category: "Snacks",
	},
	{
		itemName: "Cake Rusk",
		itemDescription: "Large",
		itemQuantity: "1",
		itemPrice: "40.00",
		category: "Snacks",
	},
	{
		itemName: "Good Day Butter",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "44.00",
		category: "Snacks",
	},
	{
		itemName: "Good Day Cashews",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "40.00",
		category: "Snacks",
	},
	{
		itemName: "Good Day Pista",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "48.00",
		category: "Snacks",
	},
	{
		itemName: "Milk Bikkis",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "5.00",
		category: "Snacks",
	},
	{
		itemName: "Exo",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
		category: "Snacks",
	},
	{
		itemName: "Tutti Frutti",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
		category: "Snacks",
	},
	{
		itemName: "Parle G Biscuit",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "25.00",
		category: "Snacks",
	},
	{
		itemName: "Khaskhas",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "28.00",
		category: "Snacks",
	},
	{
		itemName: "Flex Seed",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "18.00",
		category: "Snacks",
	},
	{
		itemName: "Roasted Channa Split",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "22.00",
		category: "Snacks",
	},
	{
		itemName: "Fenugreek Seed",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "10.00",
		category: "Snacks",
	},
	{
		itemName: "Tukmanga",
		itemDescription: "",
		itemQuantity: "1",
		itemPrice: "12.00",
		category: "Snacks",
	},
];

export const dummyData = [
	{ categoryName: "Atta", categoryData: dummyAtta, img: "atta.png" },
	{ categoryName: "Milks", categoryData: dummyMilks, img: "milk.png" },
	{ categoryName: "Tea", categoryData: dummyTea, img: "tea.png" },
	{ categoryName: "Ghee", categoryData: dummyGhee, img: "ghee.png" },
	{
		categoryName: "Pickles & Sauces",
		categoryData: dummyPickelsChutneysSauces,
		img: "sauces.png",
	},
	{ categoryName: "Oil", categoryData: dummyOil, img: "oil.png" },
	{ categoryName: "Dal", categoryData: dummyDal, img: "dal.png" },
	{
		categoryName: "Rice(small packing)",
		categoryData: dummy1kgRice,
		img: "riceSmall.png",
	},
	{
		categoryName: "Rice(big packing)",
		categoryData: dummy5kgRice,
		img: "riceBig.png",
	},
	{
		categoryName: "Spices & Condiments",
		categoryData: SpicesAndCondiments,
		img: "spices.png",
	},
	{
		categoryName: "Dry Fruits",
		categoryData: dummyDryFruits,
		img: "dryFruits.png",
	},
	{
		categoryName: "Household Items",
		categoryData: dummyPersonalCare,
		img: "houseHold.png",
	},
	{
		categoryName: "Packed Foods",
		categoryData: dummyPackedFoods,
		img: "packedFoods.png",
	},
	{ categoryName: "Snacks", categoryData: dummySnacks, img: "snacks.png" },
	{
		categoryName: "Frozen Items",
		categoryData: dummyFrozenItems,
		img: "frozenFoods.png",
	},
	{
		categoryName: "Ready To Eat",
		categoryData: dummyReadyToEat,
		img: "readyToEat.png",
	},
	{
		categoryName: "Other Grocery Items",
		categoryData: dummyOtherItems,
		img: "otherGrocery.png",
	},
];
